Add hardirqs
rust-bpf/bpf-tools pull request #5
Opened 2020-07-16 17:27 UTC by Skrinikov

briefly answer these questions:

* what problem are you trying to solve? (or if there's no problem, what's the motivation for this
  change?)
Add a hardware irq sampler
* what changes does this pull request make?
   - Add `src/hardirqs/bpf.c` and `src/hardirqs/main.rs`
   - Modify `Cargo.toml` with a new a hardiqs bin
* are there any non-obvious implications of these changes? (does it break compatibility with previous
  versions, etc)
There seems to be a bug where not all the counters are getting read. Not sure if its something with my code or the weird key size ([u_08; 40])

2020-07-16 23:10 UTC, brayniac commented
I'd like for us to add distributions to this before we merge - ideally this tool will have the bulk of the functionality that the one in iovisor/bcc repo has. It's not clear to me why some irqs are not getting counted, looks like ones that aren't have funny symbols in the name? For example, on my VM `ahci[0000:02:05.0]` does not get reported in this implementation. That seems like it would fit in the key though.

2020-07-17 19:03 UTC, Skrinikov commented
Added `-d` or `--dist` args to print log2 distribution

2020-07-22 16:15 UTC, brayniac requested changes

2020-07-22 16:15 UTC, brayniac commented on Cargo.toml
> +[[bin]]
Alphabetical order will make this easier to maintain

2020-07-22 23:19 UTC, brayniac approved these changes

2020-07-22 23:19 UTC, merged